description: "Stall configuration for specific bathroom types (mens_room, womens_room only)"
concrete_type: StallConfiguration
pattern: "bathroom_{bathroom_type}_config"
expected_properties:
  value:
    - "single"    # StallConfiguration.single
    - "multiple"  # StallConfiguration.multiple
    - ""          # Clear/remove configuration
bathroom_types:
  - "mens_room"
  - "womens_room"
example_keys:
  - "bathroom_mens_room_config"
  - "bathroom_womens_room_config"
code_references:
  - "apps/Scout/Scout/Core/Services/GroundTruthServiceExtensions.swift:403-405"
  - "packages/ScoutModels/Sources/ScoutModels/Bathrooms/StallConfiguration.swift:4-16"
  - "packages/ScoutModels/Sources/ScoutModels/Bathrooms/BathroomType.swift:49-51"
notes: |
  - Only applies to bathroom types that support stall configuration (mens_room, womens_room)
  - Value is StallConfiguration.rawValue ("single" or "multiple")
  - Empty string clears the configuration
  - Pattern: bathroom_{BathroomType.rawValue}_config